[file_hash]
"sd_xl_base_1.0.safetensors" = { "location" = "models/checkpoints/", "hash" = ["cf9d29192ef7433096a69fe5e32efba1"]}
"sd_xl_refiner_1.0.safetensors" = { "location" = "models/checkpoints/", "hash" = ["c0df90f318abf30fcd2cd233ea638251"]}
"Realistic_Vision_V5.1.safetensors" = { "location" = "models/checkpoints/", "hash" = ["03c000bbbbfede673b334897648431ba"]}
"dreamshaper_8.safetensors" = { "location" = "models/checkpoints/", "hash" = ["1bfe9fce2c2c1498bcb6fdac2e44aab5"]}
"sd_xl_refiner_1.0_0.9vae.safetensors" = { "location" = "models/checkpoints/", "hash" = ["74d31c96097471d5d3bd93a915ad0b30"]}
"pytorch_model.bin" = { "location" = "", "hash" = ["0a0900180245762f122a681839391a9b", "ac277e29ea6d70799072d1ed52ac0f79"]}
"v3_sd15_sparsectrl_rgb.ckpt" = { "location" = "models/controlnet/SD1.5/animatediff/", "hash" = ["b7d6b72ee2ba2866d167277598f27340"]}
"inpainting_diffusion_pytorch_model.fp16.safetensors" = { "location" = "models/unet/inpainting_diffusion_pytorch_model.fp16.safetensors/", "hash" = ["9c688d78a75c1d3a0b33afffdd7e72f2"]}
"vae-ft-mse-840000-ema-pruned.safetensors" = { "location" = "models/vae/", "hash" = ["418949762c3f321f2927e590e255f63c"]}
"ip_plus_composition_sd15.safetensors" = { "location" = "models/ipadapter/", "hash" = ["029d345e257b72bc7be2fdf0a2295eba"]}
"ip-adapter_sdxl.safetensors" = { "location" = "models/ipadapter/", "hash" = ["67b7f27bbf03d6b6921e520779abc212"]}
"ip-adapter-plus_sd15.bin" = { "location" = "models/ipadapter/", "hash" = ["a50be6ac20883c4969c7bb60d5f2a46b"]}
"v3_sd15_mm.ckpt" = { "location" = "models/animatediff_models/", "hash" = ["ac855686ee49fb5436c881c50a9b59ca"]}
"AnimateLCM_sd15_t2v.ckpt" = { "location" = "models/animatediff_models/", "hash" = ["b5426e509e70b1b1b13ca03f877bac2a"]}
"AnimateLCM_sd15_t2v_lora.safetensors" = { "location" = "models/loras/", "hash" = ["fb6fa0bf09bcfbe3d002ce0bfdfa7770"]}


[node_version]
"ComfyUI-Manager" = { "url" = "https://github.com/ltdrdata/ComfyUI-Manager", "commit_hash" = "7e777c5460754f4ef7a6f1ad9ef9356b89f66339"}
"ComfyUI_IPAdapter_plus" = { "url" = "https://github.com/cubiq/ComfyUI_IPAdapter_plus", "commit_hash" = "b188a6cb39b512a9c6da7235b880af42c78ccd0d"}
"comfyui-various" = { "url" = "https://github.com/jamesWalker55/comfyui-various", "commit_hash" = "cc66b62c0861314a4952eb96a6ae330f180bf6a1"}
"comfy_PoP" = { "url" = "https://github.com/picturesonpictures/comfy_PoP", "commit_hash" = "db66c9777c6ab45f9c7056f1d8f365b0d4f2b339"}
"ComfyUI-Frame-Interpolation" = { "url" = "https://github.com/Fannovel16/ComfyUI-Frame-Interpolation", "commit_hash" = "483dfe64465369e077d351ed2f1acbf7dc046864"}
"efficiency-nodes-comfyui" = { "url" = "https://github.com/jags111/efficiency-nodes-comfyui", "commit_hash" = "3ead4afd120833f3bffdefeca0d6545df8051798"}
"ComfyUI_FizzNodes" = { "url" = "https://github.com/FizzleDorf/ComfyUI_FizzNodes", "commit_hash" = "974b41cfdfde4f84d97712234d6e502f7da831fa"}
"ComfyUI-Advanced-ControlNet" = { "url" = "https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet", "commit_hash" = "74d0c56ab3ba69663281390cc1b2072107939f96"}
"ComfyUI-AnimateDiff-Evolved" = { "url" = "https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved", "commit_hash" = "83fe8d40638e3491a31fa2865107bdc14a308a35"}
"ComfyUI-VideoHelperSuite" = { "url" = "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite", "commit_hash" = "0376e577442c236fbba6ef410a4e5ec64aed5017"}
"ComfyUI_essentials" = { "url" = "https://github.com/cubiq/ComfyUI_essentials", "commit_hash" = "99aad72c84e1dac2f924941ecb12c93007512a8c"}
"steerable-motion" = { "url" = "https://github.com/banodoco/steerable-motion", "commit_hash" = "b95e9eed09741bd3f0fc3933ab45d09f6f055aae"}
"ComfyUI_tinyterraNodes" = { "url" = "https://github.com/TinyTerra/ComfyUI_tinyterraNodes", "commit_hash" = "52711d57e97c0255e6c9d627cfc0dfec4ebacf22"}


[comfy]
commit_hash = "56e8f5e4fd0a048811095f44d2147bce48b02457"


[strict_pkg_versions]
"numpy" = "1.24.4"